trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    echo "Current Directory:"
    pwd
  displayName: 'Files in current directory'

    echo "Files in Repository:"
    ls -la
  displayName: 'Inspect Repository'

- script: |
    python --version
  displayName: 'Check Python Version'
